export const SETTINGS_AI_NODE_IDS = {
  AI: 'NDX_N70',
  AGENTS: 'NDX_N71',
  SKILLS: 'NDX_N72',
} as const;

export const SETTINGS_AI_QUERY_NODE_IDS = {
  AGENTS_GROUP: 'NDX_N73',
  AGENTS_TAG: 'NDX_N74',
  SKILLS_GROUP: 'NDX_N75',
  SKILLS_TAG: 'NDX_N76',
} as const;

export const SETTINGS_AI_GROUP_NODE_IDS = {
  AI: SETTINGS_AI_NODE_IDS.AI,
  AGENTS: SETTINGS_AI_NODE_IDS.AGENTS,
  SKILLS: SETTINGS_AI_NODE_IDS.SKILLS,
} as const;
